# start with the most recently released official iron perception docker imager
FROM ros:iron-perception

ENV ROS_VERSION=2
ENV ROS_DISTRO=iron
ENV ROS_PYTHON_VERSION=3

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
# RUN rosdep init
RUN rosdep update --rosdistro $ROS_DISTRO

# setup colcon mixin and metadata
# RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml 
RUN colcon mixin update 
# RUN colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml 
RUN colcon metadata update

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends ros-iron-desktop
RUN apt-get update
RUN apt-get install -y --no-install-recommends ros-iron-navigation2
RUN apt-get install -y --no-install-recommends ros-iron-slam-toolbox
RUN apt-get install -y --no-install-recommends ros-iron-rqt*
RUN apt-get install -y --no-install-recommends ros-iron-rviz2*
RUN apt-get install -y --no-install-recommends ros-iron-rmw-cyclonedds-cpp

# install a text editor
RUN apt-get install -y --no-install-recommends nano

# add commands to terminal startup script
RUN sudo echo "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> /root/.bashrc
RUN sudo echo "source /opt/ros/iron/setup.bash" >> /root/.bashrc